#![allow(unused)]

pub const SYSCALL_GETCWD: usize = 17;
pub const SYSCALL_DUP: usize = 23;
pub const SYSCALL_DUP3: usize = 24;
pub const SYSCALL_FCNTL64: usize = 25;
pub const SYSCALL_IOCTL: usize = 29;
pub const SYSCALL_MKDIRAT: usize = 34;
pub const SYSCALL_UNLINKAT: usize = 35;
pub const SYSCALL_LINKAT: usize = 37;
pub const SYSCALL_UMOUNT2: usize = 39;
pub const SYSCALL_MOUNT: usize = 40;
pub const SYSCALL_FACCESSAT: usize = 48;
pub const SYSCALL_CHDIR: usize = 49;
pub const SYSCALL_OPENAT: usize = 56;
pub const SYSCALL_CLOSE: usize = 57;
pub const SYSCALL_PIPE: usize = 59;
pub const SYSCALL_GETDENTS64: usize = 61;
pub const SYSCALL_READ: usize = 63;
pub const SYSCALL_WRITE: usize = 64;
pub const SYSCALL_READV: usize = 65;
pub const SYSCALL_WRITEV: usize = 66;
pub const SYSCALL_SENDFILE: usize = 71;
pub const SYSCALL_PPOLL: usize = 73;
pub const SYSCALL_FSTATAT: usize = 79;
pub const SYSCALL_FSTAT: usize = 80;
pub const SYSCALL_UTIMENSAT: usize = 88;
pub const SYSCALL_EXIT: usize = 93;
pub const SYSCALL_EXIT_GROUP: usize = 94;
pub const SYSCALL_SET_TID_ADDRESS: usize = 96;
pub const SYSCALL_FUTEX: usize = 98;
pub const SYSCALL_SLEEP: usize = 101;
pub const SYSCALL_SYSLOG: usize = 116;
pub const SYSCALL_CLOCK_GETTIME: usize = 113;
pub const SYSCALL_YIELD: usize = 124;
pub const SYSCALL_KILL: usize = 129;
pub const SYSCALL_SIGACTION: usize = 134;
pub const SYSCALL_SIGPROMASK: usize = 135;
pub const SYSCALL_SIGRETURN: usize = 139;
pub const SYSCALL_TIMES: usize = 153;
pub const SYSCALL_UNAME: usize = 160;
pub const SYSCALL_GET_TIME_DAY: usize = 169;
pub const SYSCALL_GETPID: usize = 172;
pub const SYSCALL_GETPPID: usize = 173;
pub const SYSCALL_GETUID: usize = 174;
pub const SYSCALL_GETEUID: usize = 175;
pub const SYSCALL_GETTID: usize = 178;
pub const SYSCALL_SYSINFO: usize = 179;
pub const SYSCALL_SBRK: usize = 213;
pub const SYSCALL_BRK: usize = 214;
pub const SYSCALL_MUNMAP: usize = 215;
pub const SYSCALL_CLONE: usize = 220;
pub const SYSCALL_EXECVE: usize = 221;
pub const SYSCALL_MMAP: usize = 222;
pub const SYSCALL_MPROTECT: usize = 226;
pub const SYSCALL_WAIT4: usize = 260;
pub const SYSCALL_THREAD_CREATE: usize = 1000;
pub const SYSCALL_WAITTID: usize = 1002;
pub const SYSCALL_MUTEX_CREATE: usize = 1010;
pub const SYSCALL_MUTEX_LOCK: usize = 1011;
pub const SYSCALL_MUTEX_UNLOCK: usize = 1012;
pub const SYSCALL_SEMAPHORE_CREATE: usize = 1020;
pub const SYSCALL_SEMAPHORE_UP: usize = 1021;
pub const SYSCALL_SEMAPHORE_DOWN: usize = 1022;
pub const SYSCALL_CONDVAR_CREATE: usize = 1030;
pub const SYSCALL_CONDVAR_SIGNAL: usize = 1031;
pub const SYSCALL_CONDVAR_WAIT: usize = 1032;

// Not standard POSIX sys_call
pub const SYSCALL_SHUTDOWN: usize = 2000;
pub const SYSCALL_OPEN: usize = 506;

pub fn syscall_name(id: usize) -> &'static str {
    match id {
        SYSCALL_DUP => "dup",
        SYSCALL_DUP3 => "dup3",
        SYSCALL_OPEN => "open",
        SYSCALL_GET_TIME_DAY => "get_time_of_day",
        SYSCALL_GETCWD => "getcwd",
        SYSCALL_MKDIRAT => "mkdirat",
        SYSCALL_UNLINKAT => "unlinkat",
        SYSCALL_LINKAT => "linkat",
        SYSCALL_UMOUNT2 => "umount2",
        SYSCALL_MOUNT => "mount",
        SYSCALL_CHDIR => "chdir",
        SYSCALL_OPENAT => "openat",
        SYSCALL_CLOSE => "close",
        SYSCALL_READ => "read",
        SYSCALL_WRITE => "write",
        SYSCALL_FSTATAT => "fstatat",
        SYSCALL_FSTAT => "fstat",
        SYSCALL_EXIT => "exit",
        SYSCALL_SET_TID_ADDRESS => "set_tid_address",
        SYSCALL_YIELD => "yield",
        SYSCALL_KILL => "kill",
        SYSCALL_SIGACTION => "sigaction",
        SYSCALL_SIGRETURN => "sigreturn",
        SYSCALL_TIMES => "times",
        SYSCALL_UNAME => "uname",
        SYSCALL_GETPID => "getpid",
        SYSCALL_GETPPID => "getppid",
        SYSCALL_GETTID => "gettid",
        SYSCALL_BRK => "brk",
        SYSCALL_MUNMAP => "munmap",
        SYSCALL_CLONE => "clone",
        SYSCALL_EXECVE => "execve",
        SYSCALL_MMAP => "mmap",
        SYSCALL_MPROTECT => "mprotect",
        SYSCALL_WAIT4 => "wait4",
        SYSCALL_GETUID => "getuid",
        SYSCALL_SBRK => "maybe sbrk",
        SYSCALL_SIGPROMASK => "sigprocmask",
        SYSCALL_FCNTL64 => "fcntl64",
        SYSCALL_GETTID => "gettid",
        SYSCALL_EXIT_GROUP => "exitgroup",
        SYSCALL_SENDFILE => "sendfile",
        SYSCALL_PIPE => "pipe",
        SYSCALL_PPOLL => "ppoll",
        SYSCALL_CLOCK_GETTIME => "clockgettime",
        SYSCALL_IOCTL => "ioctl",
        SYSCALL_READV => "readv",
        SYSCALL_WRITEV => "writev",
        SYSCALL_SYSLOG => "syslog",
        SYSCALL_FUTEX => "futex",
        SYSCALL_GETDENTS64 => "getdents64",
        SYSCALL_FACCESSAT => "faccessat",
        SYSCALL_SYSINFO => "sysinfo",
        SYSCALL_UTIMENSAT =>"utimensat",
        // non-standard
        SYSCALL_SHUTDOWN => "shutdown",
        _ => "unknown",
    }
}
